# Enable I2C support
CONFIG_I2C=y
#eNABLE FLOATIG POINT SUPPORT
CONFIG_CBPRINTF_FP_SUPPORT=y
# ENABLE GPIO (FOR DEBUGING/LEDS)
CONFIG_GPIO=y
#ENABLE CONSOLE/LOGGING
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3